simulation:
  #seed: 42
  output_file: "output/heavy_primary-backup.csv"
  duration: 1000000

network:
  latency_min: 0.5
  latency_max: 2.0
  packet_loss_probability: 0.01

protocol:
  name: "primary_backup"
  settings:
    replication_factor: 3
  deployment:
    groups:
      - role: "PrimaryNode"
        start_id: 0
        count: 1
      - role: "BackupNode"
        start_id: 1
        count: 5

failures: []

workload:
  type: "sequential"
  start_id: 100
  clients: 250
  settings:
    num_requests_per_client: 250
    loop_client_period: 2
    request_timeout_period: 3