simulation:
  #seed: 42
  output_file: "output/heavy_lowi.csv"
  duration: 1000000

network:
  latency_min: 0.5
  latency_max: 2.0
  packet_loss_probability: 0.01

protocol:
  name: "lowi"
  settings:
    loop_leader_period: 0.005
    timeout_follower_period: 0.5
    timeout_limit: 2.5
    sync_latency: 0.001
    violation_synchronous_probability: 0.0001
  deployment:
    groups:
      - role: "LowiNode"
        start_id: 0
        count: 6

failures: []

workload:
  type: "sequential"
  start_id: 100
  clients: 10
  settings:
    num_requests_per_client: 100
    loop_client_period: 0.5
    request_timeout_period: 15
    retry_count: 5