simulation:
  output_file: "output/comparison/paxos_medium.csv"
  duration: 20000  
network:
  latency_min: 0.2
  latency_max: 1.0
  packet_loss_probability: 0.0
protocol:
  name: "basic_paxos"
  deployment:
    groups:
      - role: "ProposerNode"
        start_id: 0
        count: 2

      - role: "AcceptorNode"
        start_id: 2
        count: 4
workload:
  type: "sequential"
  start_id: 100
  clients: 5                           
  settings:
    num_requests_per_client: 20
    loop_client_period: 2
    request_timeout_period: 10
    retry_count: 3
failures: []
