simulation:
  #seed: 42
  output_file: "output/example_lowi_crash.csv"
  duration: 1000

network:
  latency_min: 0.5
  latency_max: 2.0
  packet_loss_probability: 0.01

protocol:
  name: "lowi"
  settings:
    loop_leader_period: 0.2
    timeout_follower_period: 0.5
    timeout_limit: 2.5
    sync_latency: 0.1
    violation_synchronous_probability: 0.01
  deployment:
    groups:
      - role: "LowiNode"
        start_id: 0
        count: 3

workload:
  type: "sequential"
  start_id: 100
  clients: 2
  settings:
    num_requests_per_client: 2
    loop_client_period: 2
    request_timeout_period: 5

failures:
  - time: 5.0
    action: "crash"
    target: 0