simulation:
  seed: 42
  output_file: "output/example_lowi.csv"

network:
  latency_min: 0.5
  latency_max: 2.0
  packet_loss_probability: 0.0

protocol:
  name: "lowi"
  settings:
    loop_leader_period: 0.2
    timeout_follower_period: 0.5
    timeout_limit: 2.5
    sync_latency: 0.1
    violation_synchronous_probability: 0.01
  deployment:
    groups:
      - role: "LowiNode"
        count: 3

workload:
  type: "sequential"
  clients: 1
  num_requests_per_client: 2
