simulation:
  #seed: 1234
  output_file: "output/paxos.csv"
  duration: 10000

network:
  latency_min_wan: 0
  latency_max_wan: 0
  packet_loss_probability_wan: 0

  latency_min_datacenter: 0.5
  latency_max_datacenter: 2.0
  packet_loss_probability_datacenter: 0.01

protocol:
  name: "basic_paxos"
  deployment:
    groups:
      - role: "ProposerNode"
        start_id: 0
        count: 2

      - role: "AcceptorNode"
        start_id: 2
        count: 6

workload:
  type: "sequential"
  start_id: 100
  clients: 3
  settings:
    num_requests_per_client: 5
    loop_client_period: 2
    request_timeout_period: 10