simulation:
  #seed: 1234
  output_file: "output/primary_backup.csv"
  duration: 10000

network:
  latency_min_wan: 0
  latency_max_wan: 0
  packet_loss_probability_wan: 0

  latency_min_datacenter: 0.5
  latency_max_datacenter: 2.0
  packet_loss_probability_datacenter: 0.01

protocol:
  name: "primary_backup"
  settings:
    replication_factor: 3
  deployment:
    groups:
      - role: "PrimaryNode"
        start_id: 0
        count: 1
      - role: "BackupNode"
        start_id: 1
        count: 9

workload:
  type: "sequential"
  start_id: 100
  clients: 2
  settings:
    num_requests_per_client: 2
    loop_client_period: 2
    request_timeout_period: 4