simulation:
  seed: 100
  output_file: "output/test_high_latency.csv"

network:
  latency_min: 10.0
  latency_max: 20.0
  packet_loss_prob: 0.0

nodes:
  - id: 99
    type: "ClientNode"
  - id: 0
    type: "PrimaryNode"
    config:
      backup_ids: [1]
  - id: 1
    type: "BackupNode"

workload:
  clients: [99]
  target_id: 0
  num_requests: 2
