simulation:
  seed: 300
  output_file: "output/test_heavy_workload.csv"

network:
  latency_min: 0.1
  latency_max: 0.2
  packet_loss_prob: 0.0

nodes:
  - id: 99
    type: "ClientNode"
  - id: 0
    type: "PrimaryNode"
    config:
      backup_ids: [1, 2]
  - id: 1
    type: "BackupNode"
  - id: 2
    type: "BackupNode"

workload:
  clients: [99]
  target_id: 0
  num_requests: 10
