# ASSUMPTION: 1 time unit = 1 Âµs

simulation:
  #seed: 42
  output_file: "output/saturation/primary-backup/pb_sat_70.csv"
  duration: 600000
network:
  latency_min_wan: 0
  latency_max_wan: 0
  packet_loss_probability_wan: 0

  latency_min_datacenter: 0.001
  latency_max_datacenter: 0.2
  packet_loss_probability_datacenter: 0.0001
protocol:
  name: "primary_backup"
  settings:
    replication_factor: 3
  deployment:
    groups:
      - role: "PrimaryNode"
        start_id: 0
        count: 1
      - role: "BackupNode"
        start_id: 1
        count: 5
workload:
  type: "sequential"
  start_id: 100
  clients: 70
  settings:
    num_requests_per_client: 100
    loop_client_period: 200
    request_timeout_period: 2000
    retry_count: 3