simulation:
  #seed: 42
  output_file: "output/saturation/lowi/lowi_sat_50.csv"
  duration: 1000000
network:
  latency_min_wan: 0
  latency_max_wan: 0
  packet_loss_probability_wan: 0
protocol:
  name: "lowi"
  settings:
    loop_leader_period: 0.02
    timeout_follower_period: 0.1
    timeout_limit: 1
    sync_latency: 0.5
    violation_synchronous_probability: 0.001
  deployment:
    groups:
      - role: "LowiNode"
        start_id: 0
        count: 6
workload:
  type: "sequential"
  start_id: 100
  clients: 10
  settings:
    num_requests_per_client: 100
    loop_client_period: 200
    request_timeout_period: 2000
    retry_count: 3
